### ISSUE TITLE
Chapter 2 onwards?

### ISSUE THREAD

**Issue by sharmaabhishekk** [Tuebel/BayesianMethodsForHackers#1]
Hi, thanks for this repository! 

Any chance of picking this up in the recent future? I wanted to see how a turing.jl version of the [Reddit Comments Rating](https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter4_TheGreatestTheoremNeverTold/Ch4_LawOfLargeNumbers_TFP.ipynb) problem would look like. 

Cheers!

**Comment by Tuebel** [comment]
No, sorry. I started it to play around a bit wit Turing.jl and Gen.jl. Right now I only have time for "more serious" stuff (dissertation).

**Comment by sharmaabhishekk** [comment]
No worries, I'll figure out a way. Thanks for the reply and best of luck with the dissertation :)
